// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {

  "modal-dialog-example": {
    name: "modal-dialog-example",
    description: "",
    type: "registry:example",
    registryDependencies: undefined,
    files: ["src/registry/examples/modal-dialog-example.tsx"],
    component: React.lazy(() => import("@/registry/examples/modal-dialog-example.tsx")),
    source: "",
    category: "",
    subcategory: "",
    chunks: []
  },
  "menu-dialog-example": {
    name: "menu-dialog-example",
    description: "",
    type: "registry:example",
    registryDependencies: undefined,
    files: ["src/registry/examples/menu-dialog-example.tsx"],
    component: React.lazy(() => import("@/registry/examples/menu-dialog-example.tsx")),
    source: "",
    category: "",
    subcategory: "",
    chunks: []
  },
  "accordion-dialog-example": {
    name: "accordion-dialog-example",
    description: "",
    type: "registry:example",
    registryDependencies: undefined,
    files: ["src/registry/examples/accordion-dialog-example.tsx"],
    component: React.lazy(() => import("@/registry/examples/accordion-dialog-example.tsx")),
    source: "",
    category: "",
    subcategory: "",
    chunks: []
  },
  "form-dialog-example": {
    name: "form-dialog-example",
    description: "",
    type: "registry:example",
    registryDependencies: undefined,
    files: ["src/registry/examples/form-dialog-example.tsx"],
    component: React.lazy(() => import("@/registry/examples/form-dialog-example.tsx")),
    source: "",
    category: "",
    subcategory: "",
    chunks: []
  },
  "hover-dialog-example": {
    name: "hover-dialog-example",
    description: "",
    type: "registry:example",
    registryDependencies: undefined,
    files: ["src/registry/examples/hover-dialog-example.tsx"],
    component: React.lazy(() => import("@/registry/examples/hover-dialog-example.tsx")),
    source: "",
    category: "",
    subcategory: "",
    chunks: []
  },
  "calendar-dialog-example": {
    name: "calendar-dialog-example",
    description: "",
    type: "registry:example",
    registryDependencies: undefined,
    files: ["src/registry/examples/calendar-dialog-example.tsx"],
    component: React.lazy(() => import("@/registry/examples/calendar-dialog-example.tsx")),
    source: "",
    category: "",
    subcategory: "",
    chunks: []
  },
  "combobox-dialog-example": {
    name: "combobox-dialog-example",
    description: "",
    type: "registry:example",
    registryDependencies: undefined,
    files: ["src/registry/examples/combobox-dialog-example.tsx"],
    component: React.lazy(() => import("@/registry/examples/combobox-dialog-example.tsx")),
    source: "",
    category: "",
    subcategory: "",
    chunks: []
  },
  "tiptap-dialog-example": {
    name: "tiptap-dialog-example",
    description: "",
    type: "registry:example",
    registryDependencies: undefined,
    files: ["src/registry/examples/tiptap-dialog-example.tsx"],
    component: React.lazy(() => import("@/registry/examples/tiptap-dialog-example.tsx")),
    source: "",
    category: "",
    subcategory: "",
    chunks: []
  },
}
